### ISSUE TITLE
Corrigir responsivo do editor

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua-web#25]

**Comment by domingoscapolo** [comment]
@aoscode estou a trabalhar nisso

**Comment by Aristidescosta** [comment]
@leonelsanchesdasilva Poderia explicar o que deveria ser feito?

**Comment by Aristidescosta** [comment]
Seria este o problema???
![Screenshot (153)](https://github.com/DesignLiquido/delegua-web/assets/69801513/9de314e5-42f5-4587-a2e1-478213ba690d)

**Comment by samuelrvg** [comment]
> @leonelsanchesdasilva Poderia explicar o que deveria ser feito?

@Aristidescosta Caso seja redimensionado a tela, os buttons somem, a ideia é deixar ele responsivo, onde seja possível ver o editor/buttons independente da resolução da tela.

**Comment by Aristidescosta** [comment]
> > @leonelsanchesdasilva Poderia explicar o que deveria ser feito?
> 
> @Aristidescosta Caso seja redimensionado a tela, os buttons somem, a ideia é deixar ele responsivo, onde seja possível ver o editor/buttons independente da resolução da tela.

Não sei dizer se é na minha máquina, mas os estilos não pegam.

**Comment by Aristidescosta** [comment]
@samuelrvg  a branch principal está desatualizada?

**Comment by Aristidescosta** [comment]
@samuelrvg  Para além do caso dos botões, há algum outro reparo?

Concernente a renderização, acredito que devido há alguns arquivos ele não pega ao se fazer a renderização, mas se fizer o refresh da página os estilos pegam. Poderia ser algum ficheiro ou o canva??

**Comment by leonelsanchesdasilva** [comment]
Resolvido por https://github.com/DesignLiquido/delegua-web/pull/46
