### ISSUE TITLE
adicionar modo de desenvolvimento ou framework web

### ISSUE THREAD

**Issue by thenicolau** [DesignLiquido/delegua-web#40]
Implementar um modo de desenvolvimento com HMR  ou algum framework para desenvolver de forma mais rápida e melhor a parte de front, pensei em webpack ou next/nuxt

**Comment by leonelsanchesdasilva** [comment]
A ideia deste projeto é ser o mais simples possível, usando JS simples, a linguagem e o Monaco Editor. Outros projetos mais sofisticados podem até usar HMR/frameworks JS, mas não é a ideia aqui.
