### ISSUE TITLE
Refatoração no design.

### ISSUE THREAD

**Issue by ItaloCobains** [DesignLiquido/delegua-web#7]
- Adicionar a propriedade ```cursor: pointer``` nos botões.
- Mudar a cor do cursos quando esta escrevendo algo no editor.

cc: @freezywt

**Comment by samuelrvg** [comment]
@ItaloCobains Questão do cursor já ajustei. 

Só não tive tempo de testar o segundo item, mas pelo que vi, esse seria o caminho https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color @freezywt

**Comment by ItaloCobains** [comment]
> @ItaloCobains Questão do cursor já ajustei. 
> 
> Só não tive tempo de testar o segundo item, mas pelo que vi, esse seria o caminho https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color @freezywt 

Obrigado @samuelrvg.
@freezywt está formatando o notebook dele, talvez eu mesmo resolvo esse problema amanhã.
